FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11-slim
WORKDIR /app

COPY requirements.txt /app
RUN pip install --no-cache-dir --upgrade -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/

COPY ./app /app